// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esiqdoxxbdaryblwzoye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaXFkb3h4YmRhcnlibHd6b3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTc4NzAsImV4cCI6MjA3MDAzMzg3MH0.b9fhmG6IgWhdHB4kb64A0P5IVm8PP-GXgqfLzqYMS18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});